vich_uploader:
    db_driver: orm

    mappings:
        products_images:
            uri_prefix: '%app.path.products_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.products_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true;
            delete_on_update: true;
